name: Build Velocity ChatFilter Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: gradle build

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: chatfilter-plugin
          path: build/libs/*.jar 