name: Build Velocity Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          version: 8.6

      - name: Build with Gradle (shadowJar)
        run: |
          gradlew shadowJar

      - name: Upload fat jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: velocity-plugin-fat-jar
          path: build/libs/*.jar